version: '2'
services:
 nginx:
   image: vulhub/nginx:1
   volumes:
    - ./configuration:/etc/nginx/conf.d
    - ./files/:/home/
    - ./www/:/usr/share/nginx/html/
   ports:
    - "8089:8089"
    - "8281:8281"
    - "8282:8282"
